#!/bin/bash

## Install Perl modules from MCPAN.

export PERL_MM_USE_DEFAULT=1
export PERL_EXTUTILS_AUTOINSTALL="--defaultdeps"

perl -MCPAN -e 'install Algorithm::Diff'
perl -MCPAN -e 'install Bit::Vector'
perl -MCPAN -e 'install CGI::Application'
perl -MCPAN -e 'install Carp::Clan'
perl -MCPAN -e 'install Class::AutoloadCAN'
perl -MCPAN -e 'install Class::Autouse'
perl -MCPAN -e 'install Class::Inspector'
perl -MCPAN -e 'install Clone::PP'
perl -MCPAN -e 'install Config::Simple'
perl -MCPAN -e 'install Config::Tiny'
perl -MCPAN -e 'install Data::Compare'
perl -MCPAN -e 'install Data::UUID'
perl -MCPAN -e 'install Devel::StackTrace'
perl -MCPAN -e 'install ExtUtils::CBuilder'
perl -MCPAN -e 'install ExtUtils::MakeMaker'
perl -MCPAN -e 'install File::Find::Rule'
perl -MCPAN -e 'install File::Slurp'
perl -MCPAN -e 'install Filesys::Df'
perl -MCPAN -e 'install FreezeThaw'
perl -MCPAN -e 'install GD'
perl -MCPAN -e 'install GD::Graph'
perl -MCPAN -e 'install GD::Graph::histogram'
perl -MCPAN -e 'install GD::Text'
perl -MCPAN -e 'install Genome'
perl -MCPAN -e 'install Genome::Model::Tools::Music'
perl -MCPAN -e 'install Getopt::Complete'
perl -MCPAN -e 'install HTML::Template'
perl -MCPAN -e 'install IO::String'
perl -MCPAN -e 'install IPC::Run'
perl -MCPAN -e 'install JSON'
perl -MCPAN -e 'install JSON::PP'
perl -MCPAN -e 'install JSON::XS'
perl -MCPAN -e 'install Lingua::EN::Inflect'
perl -MCPAN -e 'install List::MoreUtils'
perl -MCPAN -e 'install Module::Build'
perl -MCPAN -e 'install Module::Metadata'
perl -MCPAN -e 'install Net::HTTPServer'
perl -MCPAN -e 'install Number::Compare'
perl -MCPAN -e 'install PDF::Create'
perl -MCPAN -e 'install Parallel::ForkManager'
perl -MCPAN -e 'install Parse::CPAN::Meta'
perl -MCPAN -e 'install Parse::Range'
perl -MCPAN -e 'install Path::Class'
perl -MCPAN -e 'install Perl'
perl -MCPAN -e 'install Perl::OSType'
perl -MCPAN -e 'install PerlIO::gzip'
perl -MCPAN -e 'install Proc::ParallelLoop'
perl -MCPAN -e 'install Regexp::Common'
perl -MCPAN -e 'install Set::Scalar'
perl -MCPAN -e 'install Statistics::Distributions'
perl -MCPAN -e 'install Statistics::Regression'
perl -MCPAN -e 'install Storable'
perl -MCPAN -e 'install String::Approx'
perl -MCPAN -e 'install String::Util'
perl -MCPAN -e 'install Sub::Install'
perl -MCPAN -e 'install Sub::Name'
perl -MCPAN -e 'install Sub::Uplevel'
perl -MCPAN -e 'install Term::ReadLine'
perl -MCPAN -e 'install Test::Exception'
perl -MCPAN -e 'install Test::Fork'
perl -MCPAN -e 'install Text::CSV'
perl -MCPAN -e 'install Text::CSV::Encoded'
perl -MCPAN -e 'install Text::CSV_XS'
perl -MCPAN -e 'install Text::Diff'
perl -MCPAN -e 'install Text::Glob'
perl -MCPAN -e 'install Text::Levenshtein'
perl -MCPAN -e 'install Text::LevenshteinXS'
perl -MCPAN -e 'install Text::NSP'
perl -MCPAN -e 'install Time::HiRes'
perl -MCPAN -e 'install UR'
perl -MCPAN -e 'install XML::Generator'
perl -MCPAN -e 'install XML::SAX::Expat'
perl -MCPAN -e 'install XML::Simple'
perl -MCPAN -e 'install YAML'
perl -MCPAN -e 'install common::sense'
perl -MCPAN -e 'install version'
perl -MCPAN -e 'install Statistics::Descriptive'
perl -MCPAN -e 'install Module::Build'
perl -MCPAN -e 'install DB_File'

chmod -R 775 $MUGQIC_INSTALL_HOME/software/perl

