```{r preparation, results="hide",echo=F,message=F,warning=F}

### DEFINED OUTSIDE
# report_dir
# exploratory_dir

library(rmarkdown)
library(knitr)
library(hwriter)
library(magrittr)
options(stringsAsFactors=F)


# Directories and cp data
# unlink( file.path(report_dir,"differential_expression") , recursive = T)
dir.create( file.path(report_dir,"differential_expression"), showWarnings=F,recursive=T)
file.copy(from = exploratory_dir, to = report_dir, overwrite = T, recursive = T)
zip( file.path(report_dir,exploratory_dir,"all.zip"), files = file.path(report_dir,"exploratory") %>% list.files(full.names=T,recursive=T) )

# Create summary table
summary = file.path(report_dir,"exploratory","index.tsv") %>% read.delim(header=T,check.names=F,colClasses="character",stringsAsFactors=F,comment.char='')
summary = summary[ summary$"File" %>% basename  %in%  # some figures we don't want to show
 c("cordist_hclust_log2CPM.pdf","pca_log2CPM.pdf","top_sd_heatmap_log2CPM.pdf","top_sd_heatmap_cufflinks_logFPKMs.pdf") , ] 
summary = summary[,c("Description","File")]# we want to offer full package as zip
summary %<>% rbind(c("All Figures","exploratory/all.zip"))
summary$"File" %<>% sapply(function(fn){
	hwrite( gsub(".*\\.","",fn) ,link=fn)
})
```

##### Exploratory Analysis using filtered isoforms

Different exploratory data analysis (EDA) techniques explained above are applied to isoform expression levels, quantified  
by the RSEM log2(CPM) (counts-per-million reads). 

```{r summary_table, results="markup",echo=F,message=F,warning=F}
kable(summary,align=c("l","r"),row.names=F)
```

