#######################################
# C3G MultiQC Configuration File
#######################################

# This file can be saved either in the MultiQC installation
# directory, or as ~/.multiqc_config.yaml

# Configuration settings are taken from the following locations, in order:
# - Hardcoded in MultiQC (multiqc/utils/config.py)
# - <installation_dir>/multiqc_config.yaml
# - ~/.multiqc_config.yaml
# - Command line options

# Note that all of the values below are set to the MultiQC defaults.
# It's recommended that you delete any that you don't need.

---
title: "C3G Analysis Report"
subtitle: "Hi-C analysis using MUGQIC pipeline hicseq v1.0"
intro_text: null
report_comment: null
config_file: null
custom_logo: '${MUGQIC_PIPELINES_HOME}/bfx/report/images/logo/c3gLogo.png'
#custom_logo_url: 'https://www.example.com'
#custom_logo_title: 'C3G'
simple_output: false
template: 'default'
pandoc_template: null
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'
base_count_multiplier: 0.000001
base_count_prefix: 'Mb'
base_count_desc: 'millions'
output_fn_name: "Analysis_Summary_Report.html"
data_dir_name: 'multiqc_data'
plots_dir_name: 'multiqc_plots'
data_format: 'tsv'




# Add generic information to the top of reports
report_header_info:
    - Contact E-mail: 'services@computationalgenomics.ca'
    - Application Type: 'Hi-C Analysis'
    - Pipeline version: 'hicseq V1.0'


section_comments:
    - Trimmomatic: 'Reads are quality controlled and trimmed before alignment'
    - HiCUP: 'Trimmed reads are aligned using HiCUP'


# Order that modules should appear in report. Try to list in order of analysis.
module_order:
    - fastqc:
        module_tag:
            - RNA
            - DNA
    - trimmomatic:
        module_tag:
            - RNA
            - DNA
    - samtools:
        module_tag:
            - DNA
            - RNA
    - hicup:
        module_tag:
            - hi-c
    - homer:
        module_tag:
            - RNA
            - DNA
            - chip



# Prepend sample names with their directory. Useful if analysing the
# sample samples with different parameters.
prepend_dirs: False


# Whether to create the parsed data directory in addition to the report
make_data_dir: True

# Cleaning options for sample names. Typically, sample names are detected
# from an input filename. If any of these strings are found, they and any
# text to their right will be discarded.
# For example - file1.fq.gz_trimmed.bam_deduplicated_fastqc.zip
# would be cleaned to 'file1'
# Two options here - fn_clean_exts will remove the defaults,
# extra_fn_clean_exts will append to the defaults
extra_fn_clean_exts:
    - .gz
    - .fastq
    - .fq
    - .bam
    - .sam
    - .sra
    - _tophat
    - _star_aligned
    - _fastqc
    - type: remove
      pattern: '.sorted'
    - type: regex
      pattern: '^Sample_\d+'
    - type: regex_keep
      pattern: '[A-Z]{3}[1-9]{4}[A,B][1-9]'

# Ignore these files / directories / paths when searching for logs
fn_ignore_files:
    - .DS_Store
fn_ignore_dirs:
    - annoying_dirname
fn_ignore_paths:
    - '*/path/to/*_files/'

# Ignore files larger than this when searcing for logs (bytes)
log_filesize_limit: 5000000

# MultiQC skips a couple of debug messages when searching files as the
# log can get very verbose otherwise. Re-enable here to help debugging.
report_readerrors: False
report_imgskips: False

# Opt-out of remotely checking that you're running the latest version
no_version_check: False

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 50      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 500              # Swap tables for a beeswarm plot above this

# Overwrite module filename search patterns. See multiqc/utils/search_patterns.yaml
# for the defaults. Remove a default by setting it to null.
sp:
    star:
        fn: '*Log.final.out'
    trimmomatic:
        contents: 'Trimmomatic'




