%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}}}%%

        %% GenPipes Schema for dnaseq.py
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/dnaseq/
        %% Author Shaloo Shalini <shalz@hotmail.com>
        %% -t mugqic

        graph LR
        Node1{{ 1. <br/> Picard <br/>SAM <br/>to FASTQ }}:::nodefill
        Node2{{ 2. <br/> Skewer <br/>Trimming }}:::nodefill
        Node3{{ 3. <br/> BWA <br/>SAMbamba <br/>sort <br/>SAM }}:::nodefill
        Node4{{ 4. <br/> SAMbamba <br/>merge <br/>SAM <br/>files }}:::nodefillblack
        Node5{{ 5. <br/> GATK <br/>indel <br/>re-aligner }}:::nodefill
        Node6{{ 6. <br/> SAMBAM <br/>merge <br/>realigned }}:::nodefill
        Node7{{ 7. <br/> Picard <br/>Mark <br/>Duplicates }}:::nodefill
        Node8{{ 8. <br/> Recalibration }}:::nodefill
        Node9{{ 9. <br/> GATK <br/>Haplotype <br/>Caller }}:::nodefill
        Node10{{ 10. <br/> Merge & <br/>call-individual <br/>GVCF}}:::nodefill
        Node11{{ 11. <br/> Combine <br/>GVCF }}:::nodefill
        Node12{{ 12. <br/> Merge and <br/>call-combined <br/>GVCF }}:::nodefill
        Node13{{ 13. <br/> Variant <br/>Recalibrator }}:::nodefill
        Node14{{ 14. <br/> HC caller <br/>decompose & <br/>normalize }}:::nodefill
        Node15{{ 15. <br/> HC caller <br/>flag <br/>mappability }}:::nodefill
        Node16{{ 16. <br/> HC caller <br/>SNP ID <br/>annotation }}:::nodefill
        Node17{{ 17. <br/> HC caller <br/>SNP effect  }}:::nodefill
        Node18{{ 18. <br/> HC caller <br/>dbnsfp <br/>annotation }}:::nodefill
        Node19{{ 19. <br/> HC caller <br/>Gemini <br/>Annotation }}:::nodefill
        Node20{{ 20. <br/> DNA <br/>Picard <br/>Metrics }}:::nodefill
        Node21{{ 21. <br/> DNA <br/>Sample <br/>Qualimap }}:::nodefill
        Node22{{ 22. <br/> DNA <br/>FASTQC }}:::nodefill
        Node23{{ 23. <br/> Picard <br/>Calculate <br/>HS Metrics }}:::nodefill
        Node24{{ 24. <br/> Metrics }}:::nodefill
        Node25{{ 25. <br/> GATK <br/>Callable <br/>Loci }}:::nodefill
        Node26{{ 26. <br/> Extract <br/>Common <br/>SNP <br/>Frequency }}:::nodefill
        Node27{{ 27. <br/> BAF <br/>Plot }}:::nodefill
        Node28{{ 28. <br/> Run <br/>MultiQC }}:::nodefill
        Node29{{ 29. <br/> Cram <br/>Output }}:::nodefill
        Node30{{ 30. <br/> Symlink <br/>FASTQ }}:::nodefill
        Node31{{ 31. <br/> Symlink <br/>final <br/>BAM }}:::nodefill
        Node32{{ 32. <br/> NGScheckmate }}:::nodefill
        Node33{{ 33. <br/> Verify <br/>BAM ID }}:::nodefill
        Node34{{ 34. <br/> VCFTools <br/>missing <br/>individual }}:::nodefill
        Node35{{ 35. <br/> VCFTools <br/>depth <br/>individual }}:::nodefill
        Node36{{ 36. <br/> GATK <br/>Sample <br/>Fingerprint }}:::nodefill
        Node37{{ 37. <br/> GATK <br/>Cluster <br/>Fingerprint }}:::nodefill

        Input1[[fa:fa-file-archive-o .BAM]]
        Input2[[fa:fa-file-archive-o .FASTQ]]

        RecalibOP([fa:fa-sticky-note-o Report ])
        MultiQCOP([fa:fa-sticky-note-o Report ])
        CramOP([fa:fa-sticky-note-o Report ])

        Input1 --> Node1 -.-> Node2
        Input2 --> Node2

        Node2 -.-> Node3 -.-> Node4 -.-> Node5 -.-> Node6 -.-> Node7
        Node7 -.-> Node8 & Node9 & Node22 & Node23 & Node24 & Node25 & Node26 & Node30
        Node9 -.-> Node10 -.-> Node11 -.-> Node12 -.-> Node13 -.-> Node14 -.-> Node15 -.-> Node16 -.-> Node17 -.-> Node18 -.-> Node19
        Node8 -.-> Node20 & Node29 & Node33 & Node36 -.-> Node37
        Node10 -.-> Node32
        Node12 -.-> Node34
        Node20 -.-> Node21 & Node28
        Node22 -.-> Node28
        Node26 -.-> Node27
        Node30 -.-> Node31
        Node34 -.-> Node35

        Node8 --> RecalibOP
        Node28 --> MultiQCOP
        Node29 ---> CramOP

        subgraph readSetSteps[" "]
          Node1
          Node2
          Node3
          MTSOutput
        end
        subgraph sampleSetSteps[" "]
          Node5
          Node6
          Node7
          Node8
          Node9
          Node10
          Node11
          Node12
          Node13
          Node14
          Node15
          Node16
          Node17
          Node18
          Node19
          Node20
          Node21
          Node22
          Node23
          Node24
          Node25
          Node26
          Node27
          Node28
          Node29
          Node30
          Node31
          Node32
          Node33
          Node34
          Node35
          Node36
          Node37
          subgraph combo2021[" "]
            Node20
            Node21
          end
          subgraph combo222324[" "]
            Node22
            Node23
            Node24
          end
          subgraph combo2526[" "]
            Node25
            Node26
          end
          subgraph combo3031[" "]
            Node30
            Node31
          end
          subgraph combo3435[" "]
            Node34
            Node35
          end
          RecalibOP
          MultiQCOP
          CramOP
        end

        classDef greenRect fill:#E4FBF4,stroke:white
        class readSetSteps greenRect
        classDef blueRect fill:#DEF6FC,stroke:white
        class sampleSetSteps blueRect
        classDef transparentRect fill:#DEF6FC,stroke:gray
        class combo2021 transparentRect
        class combo222324 transparentRect
        class combo2526 transparentRect
        class combo3031 transparentRect
        class combo3435 transparentRect
        classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
        classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
