%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}, 'fontFamily': 'Montserrat', 'fontSize': 10}}%%

        %% GenPipes Pipeline workflow legend
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines
        %% Author Shaloo Shalini <shalz@hotmail.com>

graph BT
     subgraph arrlegend [" "]
       Step{{ Pipeline <br/> Step }}
       BStep{{ Step on <br> multiple <br/> Readsets/Samples }}
       Input[[fa:fa-file-archive-o Data File]]
       PipeStep1[ Steps performed <br/>on Readsets ]
       PipeStep2[ Steps performed <br/> on samples ]
       empty1[" "]:::whiteRect --> empty2["Input/Output"]:::whiteRect
       empty5[" "]:::whiteRect -.-> empty6["Step Dependency "]:::whiteRect
       empty3[" "]:::whiteRect ==> empty4["Alternative<br/>Entry"]:::whiteRect
     end

  classDef greenRect fill:#E4FBF4,stroke:white
  classDef blueRect fill:#DEF6FC,stroke:white
  classDef whiteRect fill:white,stroke:white
  classDef gborder fill:white,stroke:gray
  classDef nodefill fill:#ffffff,stroke:black,stroke-width:1px
  classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:1px

  class PipeStep1 greenRect
  class PipeStep2 blueRect
  class arrlegend gborder
  class Step nodefill
  class BStep nodefillblack
