%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}, 'fontFamily': 'Montserrat', 'fontSize': 10}}}%%

        %% GenPipes Schema for methylseq.py
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/methylseq/
        %% Author Shaloo Shalini <shalz@hotmail.com>

        graph LR
          InputBAM[[fa:fa-file-archive-o .BAM]]
          InputFASTQ[[fa:fa-sticky-note-o .FASTQ ]]
          Output([fa:fa-sticky-note-o Report ])
          MetricsOP([fa:fa-sticky-note-o Report ])
          QCReport([fa:fa-sticky-note-o Report])
          DAReport([fa:fa-sticky-note-o Report])

          Node1{{ 1. <br/> Picard<br/>SAM<br/>to<br/>FASTQ }}:::nodefill
          Node2{{ 2. <br/> Trimmomatic }}:::nodefill
          Node3{{ 3. <br/> Merge <br/> Trimmomatic <br/> Stats }}:::nodefillblack
          Node4{{ 4. <br/> Dragen <br/> Align }}:::nodefill
          Node5{{ 5. <br/> Add <br/> BAM <br/> UMI }}:::nodefill
          Node6{{ 6. <br/> SAMbamba <br/> merge <br/> SAM <br/> files }}:::nodefillblack
          Node7{{ 7. <br/> Sort <br/> Dragen <br/> SAM }}:::nodefill
          Node8{{ 8. <br/> Metrics }}:::nodefill
          Node9{{ 9. <br/> Dragen <br/> Methylation <br/> Call }}:::nodefill
          Node10{{ 10. <br/> Split <br/> Dragen Methylation <br/> Report }}:::nodefill
          Node11{{ 11. <br/> Methylation <br/> Profile }}:::nodefill
          Node12{{ 12. <br/> Dragen <br/> BED Graph }}:::nodefill
          Node13{{ 13. <br/> Wiggle <br/> Tracks }}:::nodefill
          Node14{{ 14. <br/> IHEC <br/> Sample <br/> Metrics <br/> Report }}:::nodefill
          Node15{{ 15. <br/> BIS <br/> SNP  }}:::nodefill
          Node16{{ 16. <br/> Filter <br/> SNP <br/> CPG }}:::nodefill
          Node17{{ 17. <br/> Prepare <br/> Methylkit }}:::nodefill
          Node18{{ 18. <br/> Methylkit Differential <br/> Analysis }}:::nodefill
          Node19{{ 19. <br/> MultiQC }}:::nodefill
          Node20{{ 20. <br/> Cram <br/> Output }}:::nodefill

          InputBAM --> Node1 -.-> Node2
          InputFASTQ --> Node2

          Node2 -.-> Node3 & Node4 & Node14
          Node3 -.-> Node4 & Node6 & Node12
          Node4 -.-> Node5 -.-> Node6
          Node4 -.-> Node16 & Node19
          Node6 -.-> Node7 & Node9 & Node12 & Node14
          Node7 -.-> Node8 & Node9 & Node10 & Node12 & Node13 & Node14 & Node15 & Node20
          Node8 -.-> Node12 & Node14 & Node19
          Node9 -.-> Node10 -.-> Node11 -.-> Node12 -.-> Node13
          Node11 -.-> Node12 & Node14 & Node16
          Node16 -.-> Node17 -.-> Node18

          Node8 --> MetricsOP
          Node18 --> DAReport
          Node19 --> QCReport
          Node20 --> Output

          subgraph readSetSteps[" "]
            Node1
            Node2
          end

          subgraph sampleSetSteps[" "]
            Node4
            Node5
            Node6
            Node7
            Node8
            Node9
            Node10
            Node11
            Node12
            Node13
            Node14
            Node15
            Node16
            Node17
            Node18
            Node19
            Node20
            MetricsOP
            QCReport
            DAReport
            Output
          end

          classDef greenRect fill:#E4FBF4,stroke:white
          class readSetSteps greenRect
          classDef blueRect fill:#DEF6FC,stroke:white
          class sampleSetSteps blueRect
          classDef inputfill fill:#ffffff,stroke:gray,stroke-width:1px
          classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
          classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
          class InputBAM inputfill
          class InputFASTQ inputfill
