%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}}}%%

        %% GenPipes Schema for rnaseq_denovo_assembly.py
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/rnaseq_denovo_assembly/
        %% Author Shaloo Shalini <shalz@hotmail.com>

        graph LR

          Node1{{ 1. <br/> Picard <br/> SAM <br/>to <br/> FASTQ }}:::nodefill
          Node2{{ 2. <br/> Trimmomatic }}:::nodefill
          Node3{{ 3. <br/> Merge <br/> Trimmomatic <br/>Stats }}:::nodefillblack
          Node4{{ 4. <br/> Insilico<br/>Read<br/>Normalization }}:::nodefill
          Node5{{ 5. <br/> Insilico<br/>Read<br/>Normalization<br/>All }}:::nodefill
          Node6{{ 6. <br/> Trinity }}:::nodefill
          Node7{{ 7. <br/> Exonerate <br/> FASTA <br/> Split }}:::nodefill
          Node8{{ 8. <br/> BLASTX <br/> Trinity <br/> UniProt }}:::nodefill
          Node9{{ 9. <br/> BLASTX <br/> Trinity <br/> UniProt <br/> Merge}}:::nodefillblack
          Node10{{ 10. <br/> Transdecoder Step }}:::nodefill
          Node11{{ 11. <br/> HMMER }}:::nodefill
          Node12{{ 12. <br/> RNAmmer }}:::nodefill
          Node13{{ 12. <br/> BLAST <br/> Transdecoder <br/> UniProt }}:::nodefill
          Node14{{ 14. <br/> SignalP }}:::nodefill
          Node15{{ 15. <br/> TMHMM }}:::nodefill
          Node16{{ 16. <br/> Trinotate }}:::nodefill
          Node17{{ 17. <br/> Abund <br/> Prep <br/> Reference }}:::nodefill
          Node18{{ 18. <br/> Estimate <br/> Abundance }}:::nodefill
          Node19{{ 19. <br/> GQSeq <br/> Util <br/> Exploratory <br/> Analysis }}:::nodefill
          Node20{{ 20. <br/> Differential <br/> Expression }}:::nodefill
          Node21{{ 21. <br/> Filter <br/> Annotated <br/> components }}:::nodefill
          Node22{{ 22. <br/> GQSeq <br/> Exploratory <br/> Analysis }}:::nodefill
          Node23{{ 23. <br/> Differential <br/> Expression <br/> Filtered }}:::nodefill

          Input1[[fa:fa-file-archive-o .BAM]]
          Input2[[fa:fa-file-archive-o .FASTQ]]
          IROP([fa:fa-sticky-note-o Report ])
          BTOP([fa:fa-sticky-note-o Report ])
          TrinityOP([fa:fa-sticky-note-o Report ])
          TrinotateOP([fa:fa-sticky-note-o Report ])
          Output([fa:fa-sticky-note-o Report ])

          Input1 --> Node1 -.-> Node2
          Input2 --> Node2

          Node2 -.-> Node3 & Node4 & Node18
          Node4 -.-> Node5 -.-> Node6 -.-> Node7 -.-> Node8 -.-> Node9
          Node6 & Node9 & Node10 & Node11 & Node12 & Node14 & Node15 -.-> Node16
          Node6 -.-> Node10 & Node12 & Node17 & Node18 & Node21 & Node23
          Node10 -.-> Node11 & Node13 & Node14 & Node15
          Node16 -.-> Node20
          Node18 -.-> Node19 & Node20 & Node21 & Node22 & Node23
          Node21 -.-> Node22

          Node5 --> IROP
          Node6 --> TrinityOP
          Node9 --> BTOP
          Node16 --> TrinotateOP
          Node22 --> Output

          subgraph readSetSteps[" "]
            Node1
            Node2
          end
          subgraph sampleSetSteps[" "]
            Node4
            Node5
            Node6
            Node7
            Node8
            Node9
            Node10
            Node11
            Node12
            Node13
            Node14
            Node15
            Node16
            Node17
            Node18
            Node19
            Node20
            Node21
            Node22
            Node23
            IROP
            BTOP
            TrinityOP
            TrinotateOP
            Output
          end
          classDef greenRect fill:#E4FBF4,stroke:white
          class readSetSteps greenRect
          classDef blueRect fill:#DEF6FC,stroke:white
          class sampleSetSteps blueRect
          classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
          classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
