%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}}}%%

        %% GenPipes Schema for rnaseq.py
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/rnaseq/
        %% Author Shaloo Shalini <shalz@hotmail.com>
        %% -t variants

        graph LR
        Node1{{ 1. <br/> Picard <br/> SAM <br/> to <br/> FASTQ }}:::nodefill
        Node2{{ 2. <br/> Skewer Trimming }}:::nodefill
        Node3{{ 3. <br/> SortMerna }}:::nodefill
        Node4{{ 4. <br/> Star <br/> Processing }}:::nodefill
        Node5{{ 5. <br/> Picard Merge <br/> SAM <br/> files }}:::nodefillblack
        Node6{{ 6. <br/> Mark <br/> Duplicates }}:::nodefill
        Node7{{ 7. <br/> Split N<br/> Trim }}:::nodefill
        Node8{{ 8. Merge Split N <br/> Trim Files }}:::nodefill
        Node9{{ 9. GATK Indel<br/>Realigner }}:::nodefill
        Node10{{ 10. SAMBAM Merge<br/>Realigned }}:::nodefill
        Node11{{ 11. Recalibration }}:::nodefill
        Node12{{ 12. GATK Haplotype<br/>Caller }}:::nodefill
        Node13{{ 13. Merge HC<br/>VCF }}:::nodefill
        Node14{{ 14. Run<br/>VCFanno }}:::nodefill
        Node15{{ 15. Decompose<br/>&<br/> Normalize }}:::nodefill
        Node16{{ 16. Filter<br/>GATK }}:::nodefill
        Node17{{ 17. Report<br/>CPSR }}:::nodefill
        Node18{{ 18. Report<br/>PCGR }}:::nodefill
        Node19{{ 19. Run Star<br/> Fusion}}:::nodefill
        Node20{{ 20. Run Arriba}}:::nodefill
        Node21{{ 21. Run Annofuse}}:::nodefill
        Node22{{ 22. Picard RNA<br/>Metrics }}:::nodefill
        Node23{{ 23. Estimate<br/>Ribosomal RNA}}:::nodefill
        Node24{{ 24. RNASeqC2 }}:::nodefill
        Node25{{ 25. RSeqC }}:::nodefill
        Node26{{ 26. GATK<br/>Callable Loci }}:::nodefill
        Node27{{ 27. <br/> Wiggle }}:::nodefill
        Node28{{ 28. <br/> MultiQC }}:::nodefill
        Node29{{ 29. <br/> Cram <br/> Output }}:::nodefill

        Input1[[fa:fa-file-archive-o .BAM]]
        Input2[[fa:fa-file-archive-o .FASTQ]]

        StarOP([fa:fa-sticky-note-o Report ])
        Rseqc2OP([fa:fa-sticky-note-o Report ])
        CPSROP([fa:fa-sticky-note-o Report ])
        PCGROP([fa:fa-sticky-note-o Report ])
        MultiQCOP([fa:fa-sticky-note-o Report ])

        Input1 --> Node1 -.-> Node2
        Input2 --> Node2

        Node2 -.-> Node3 & Node4 & Node19 & Node20
        Node4 -.-> Node5 -.->Node6 -.> Node7 -.-> Node8
        Node4 -.-> Node23
        Node6 -.-> Node22 & Node24 & Node27 & Node29
        Node7 -.-> Node9 -.-> Node10
        Node9 -.-> Node11 -.-> Node12 -.-> Node13 -.-> Node14 -.-> Node15 -.-> Node16 -.-> Node17 -.-> Node18
        Node11-.-> Node25 & Node26
        Node19 & Node20 -.-> Node21
        Node2 & Node3 & Node4 & Node6 & Node11 & Node19 & Node20 & Node22 & Node23 & Node25 -.-> Node28

        Node4 --> StarOP
        Node17 --> CPSROP
        Node18 --> PCGROP
        Node24 --> Rseqc2OP
        Node28 --> MultiQCOP

        subgraph readSetSteps[" "]
          Node1
          Node2
          Node3
          Node4
          StarOP
        end
        subgraph sampleSetSteps[" "]
          Node6
          Node7
          Node8
          Node9
          Node10
          Node11
          Node12
          Node13
          Node14
          Node15
          Node16
          Node17
          Node18
          Node19
          Node20
          Node21
          Node22
          Node23
          Node24
          Node25
          Node26
          Node27
          Node28
          Node29

          Rseqc2OP
          CPSROP
          PCGROP
          MultiQCOP
        end
        classDef greenRect fill:#E4FBF4,stroke:white
        class readSetSteps greenRect
        classDef blueRect fill:#DEF6FC,stroke:white
        class sampleSetSteps blueRect
        classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
        classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
