%%{init: {'theme': 'base', 'themeVariables': { 'lineColor': '#404040'}}}%%

        %% GenPipes Schema for rnaseq_denovo_assembly.py
        %% Ref: https://bitbucket.org/mugqic/genpipes/src/master/pipelines/rnaseq_denovo_assembly/
        %% Author Shaloo Shalini <shalz@hotmail.com>

        graph LR
          Node1{{ 1. <br/> Picard <br/> SAM <br/>to <br/> FASTQ }}:::nodefill
          Node2{{ 2. <br/> Merge <br/> FASTQ }}:::nodefillblack
          Node3{{ 3. <br/> Seq2Fun }}:::nodefill
          Node4{{ 4. <br/> Differential <br/> Expression <br/>Seq2Fun }}:::nodefill
          Node5{{ 5. <br/> Pathway <br/> Enrichment }}:::nodefill

          Input1[[fa:fa-file-archive-o .BAM]]
          Input2[[fa:fa-file-archive-o .FASTQ]]

          Output([fa:fa-sticky-note-o Report ])
          Seq2Fun([fa:fa-sticky-note-o Report ])

          Input1 --> Node1
          Input2 --> Node2

          Node1 -.-> Node2 -.-> Node3 -.-> Node4 -.-> Node5

          Node3 --> Seq2Fun
          Node5 --> Output

          subgraph readSetSteps[" "]
            Node1
          end
          subgraph sampleSetSteps[" "]
            Node3
            Node4
            Node5
            Seq2Fun
            Output
          end

          classDef greenRect fill:#E4FBF4,stroke:white
          class readSetSteps greenRect
          classDef blueRect fill:#DEF6FC,stroke:white
          class sampleSetSteps blueRect
          classDef nodefill fill:#ffffff,stroke:gray,stroke-width:2px
          classDef nodefillblack fill:black,stroke:black,color:white,stroke-width:2px
