# AUTOMATICALLY GENERATED by `shtab`



complete genpipes \
        'c/--/(batch clean config container design force force_mem_per_cpu genpipes_file help job-scheduler json-pt log no-json output-dir pairs profyle readsets sanity-check steps type version wrap)/' \
        'c/-/(- b c d f g h j l o p r s t v)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(chipseq atacseq)/' \
        'n/--type/(chipseq atacseq)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(germline_snv germline_sv germline_high_cov somatic_tumor_only somatic_fastpass somatic_ensemble somatic_sv)/' \
        'n/--type/(germline_snv germline_sv germline_high_cov somatic_tumor_only somatic_fastpass somatic_ensemble somatic_sv)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(bismark hybrid dragen)/' \
        'n/--type/(bismark hybrid dragen)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(default basecalling)/' \
        'n/--type/(default basecalling)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(stringtie variants cancer)/' \
        'n/--type/(stringtie variants cancer)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(trinity seq2fun)/' \
        'n/--type/(trinity seq2fun)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'p/1/(ampliconseq chipseq covseq dnaseq methylseq nanopore nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light)/' \
        'p/*/()/'
