# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to somewhere (e.g. ~/.local/share/tcsh_completion/genpipes).
# 2) Add the following line to your .cshrc or .tcshrc:
#    source ~/.local/share/tcsh_completion/genpipes
# See also: https://github.com/tcsh-org/tcsh/blob/master/complete.tcsh



complete genpipes \
        'c/-s=/(bash zsh tcsh fish powershell)/' \
        'c/--print-completion=/(bash zsh tcsh fish powershell)/' \
        'c/-c=/f/' \
        'c/--config=/f/' \
        'c/-j=/(pbs batch daemon slurm)/' \
        'c/--job-scheduler=/(pbs batch daemon slurm)/' \
        'c/-l=/(debug info warning error critical)/' \
        'c/--log=/(debug info warning error critical)/' \
        'c/-o=/d/' \
        'c/--output-dir=/d/' \
        'c/-r=/f/' \
        'c/--readsets=/f/' \
        'c/-d=/f/' \
        'c/--design=/f/' \
        'c/-t=/(chipseq atacseq)/' \
        'c/--type=/(chipseq atacseq)/' \
        'c/-p=/f/' \
        'c/--pairs=/f/' \
        'c/-t=/(germline_snv germline_sv germline_high_cov somatic_tumor_only somatic_fastpass somatic_ensemble somatic_sv somatic_ensemble_sv)/' \
        'c/--type=/(germline_snv germline_sv germline_high_cov somatic_tumor_only somatic_fastpass somatic_ensemble somatic_sv somatic_ensemble_sv)/' \
        'c/-t=/(nanopore nanopore_paired_somatic revio)/' \
        'c/--type=/(nanopore nanopore_paired_somatic revio)/' \
        'c/-t=/(bismark gembs hybrid dragen)/' \
        'c/--type=/(bismark gembs hybrid dragen)/' \
        'c/-t=/(default basecalling)/' \
        'c/--type=/(default basecalling)/' \
        'c/-t=/(stringtie variants cancer)/' \
        'c/--type=/(stringtie variants cancer)/' \
        'c/-b=/f/' \
        'c/--batch=/f/' \
        'c/-t=/(trinity seq2fun)/' \
        'c/--type=/(trinity seq2fun)/' \
        'c/--loglevel=/(ERROR WARNING INFO CRITICAL)/' \
        'c/-S=/(slurm pbs)/' \
        'c/-p=/(ampliconseq chipseq covseq dnaseq methylseq longread_dnaseq nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light)/' \
        'c/--pipeline=/(ampliconseq chipseq covseq dnaseq methylseq longread_dnaseq nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light)/' \
        'c/--/(batch clean config container design force force_mem_per_cpu genpipes_file help job-scheduler job_name json-pt json_outfile log loglevel metrics output-dir pairs pipeline print-completion profyle quiet readset readset_names readsets sample_names sanity-check status steps tsv type version wrap)/' \
        'c/-/(- S b c d f g h j l m n o p q r s t u v)/' \
        'n/-s/(bash zsh tcsh fish powershell)/' \
        'n/--print-completion/(bash zsh tcsh fish powershell)/' \
        'n/-c/f/' \
        'n/--config/f/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-o/d/' \
        'n/--output-dir/d/' \
        'n/-r/f/' \
        'n/--readsets/f/' \
        'n/-d/f/' \
        'n/--design/f/' \
        'n/-t/(chipseq atacseq)/' \
        'n/--type/(chipseq atacseq)/' \
        'n/-p/f/' \
        'n/--pairs/f/' \
        'n/-t/(germline_snv germline_sv germline_high_cov somatic_tumor_only somatic_fastpass somatic_ensemble somatic_sv somatic_ensemble_sv)/' \
        'n/--type/(germline_snv germline_sv germline_high_cov somatic_tumor_only somatic_fastpass somatic_ensemble somatic_sv somatic_ensemble_sv)/' \
        'n/-t/(nanopore nanopore_paired_somatic revio)/' \
        'n/--type/(nanopore nanopore_paired_somatic revio)/' \
        'n/-t/(bismark gembs hybrid dragen)/' \
        'n/--type/(bismark gembs hybrid dragen)/' \
        'n/-t/(default basecalling)/' \
        'n/--type/(default basecalling)/' \
        'n/-t/(stringtie variants cancer)/' \
        'n/--type/(stringtie variants cancer)/' \
        'n/-b/f/' \
        'n/--batch/f/' \
        'n/-t/(trinity seq2fun)/' \
        'n/--type/(trinity seq2fun)/' \
        'n/--loglevel/(ERROR WARNING INFO CRITICAL)/' \
        'n/-S/(slurm pbs)/' \
        'n/-p/(ampliconseq chipseq covseq dnaseq methylseq longread_dnaseq nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light)/' \
        'n/--pipeline/(ampliconseq chipseq covseq dnaseq methylseq longread_dnaseq nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light)/' \
        'p/1/(ampliconseq chipseq covseq dnaseq longread_dnaseq methylseq nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light tools)/' \
        'p/2/(chunk_genpipes csvToreadset job2json_project_tracking log_report submit_genpipes chunk_and_submit_genpipes get_wrapper validate_genpipes wizard)/' \
        'p/*/()/'
