# AUTOMATICALLY GENERATED by `shtab`



complete genpipes \
        'c/--/(report readsets design type version sanity-check pairs enzyme clean steps config force help container log no-json job-scheduler genpipes_file output-dir wrap profyle)/' \
        'c/-/(g p r t e o j h l v s c d f -)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(qiime dada2)/' \
        'n/--type/(qiime dada2)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(chipseq atacseq)/' \
        'n/--type/(chipseq atacseq)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(mugqic mpileup light sv)/' \
        'n/--type/(mugqic mpileup light sv)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-e/(DpnII HindIII NcoI MboI Arima)/' \
        'n/--enzyme/(DpnII HindIII NcoI MboI Arima)/' \
        'n/-t/(hic capture)/' \
        'n/--type/(hic capture)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(default basecalling)/' \
        'n/--type/(default basecalling)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(stringtie cufflinks)/' \
        'n/--type/(stringtie cufflinks)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(trinity seq2fun)/' \
        'n/--type/(trinity seq2fun)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-j/(pbs batch daemon slurm)/' \
        'n/--job-scheduler/(pbs batch daemon slurm)/' \
        'n/-l/(debug info warning error critical)/' \
        'n/--log/(debug info warning error critical)/' \
        'n/-t/(fastpass ensemble sv)/' \
        'n/--type/(fastpass ensemble sv)/' \
        'p/1/(ampliconseq chipseq covseq dnaseq dnaseq_high_coverage epiqc hicseq methylseq nanopore nanopore_covseq rnaseq rnaseq_denovo_assembly rnaseq_light tumor_pair)/' \
        'p/*/()/'
