# AUTOMATICALLY GENERATED by `shtab`

_shtab_genpipes_subparsers=('ampliconseq' 'chipseq' 'covseq' 'dnaseq' 'longread_dnaseq' 'methylseq' 'nanopore_covseq' 'rnaseq' 'rnaseq_denovo_assembly' 'rnaseq_light' 'tools')
_shtab_genpipes_tools_subparsers=('chunk_genpipes' 'csvToreadset' 'job2json_project_tracking' 'log_report' 'submit_genpipes' 'get_wrapper' 'validate_genpipes')

_shtab_genpipes_option_strings=('-h' '--help' '-v' '--version' '-s' '--print-completion')
_shtab_genpipes_ampliconseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version')
_shtab_genpipes_chipseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-t' '--type')
_shtab_genpipes_covseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version')
_shtab_genpipes_dnaseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-p' '--pairs' '--profyle' '-t' '--type')
_shtab_genpipes_longread_dnaseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-t' '--type')
_shtab_genpipes_methylseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-t' '--type')
_shtab_genpipes_nanopore_covseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-t' '--type')
_shtab_genpipes_rnaseq_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-t' '--type' '-b' '--batch')
_shtab_genpipes_rnaseq_denovo_assembly_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version' '-t' '--type' '-b' '--batch')
_shtab_genpipes_rnaseq_light_option_strings=('-h' '--help' '--clean' '-c' '--config' '--container' '-f' '--force' '--force_mem_per_cpu' '--genpipes_file' '-g' '-j' '--job-scheduler' '--json-pt' '-l' '--log' '-o' '--output-dir' '--sanity-check' '-s' '--steps' '--wrap' '-r' '--readsets' '-d' '--design' '-v' '--version')
_shtab_genpipes_tools_option_strings=('-h' '--help')
_shtab_genpipes_tools_chunk_genpipes_option_strings=('-h' '--help' '-n')
_shtab_genpipes_tools_csvToreadset_option_strings=('-h' '--help')
_shtab_genpipes_tools_job2json_project_tracking_option_strings=('-h' '--help' '-s' '--sample_names' '-r' '--readset_names' '-j' '--job_name' '-m' '--metrics' '-o' '--json_outfile' '-f' '--status')
_shtab_genpipes_tools_log_report_option_strings=('-h' '--help' '--loglevel' '--tsv' '--quiet' '-q')
_shtab_genpipes_tools_submit_genpipes_option_strings=('-h' '--help' '-n' '-s' '-S' '-l')
_shtab_genpipes_tools_get_wrapper_option_strings=('-h' '--help' '--version' '-v')
_shtab_genpipes_tools_validate_genpipes_option_strings=('-h' '--help' '-r' '--readset' '-d' '--design' '-p' '--pipeline')

_shtab_genpipes_ampliconseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_ampliconseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_ampliconseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_ampliconseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_ampliconseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_ampliconseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_ampliconseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_ampliconseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_chipseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_chipseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_chipseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_chipseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_chipseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_chipseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_chipseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_chipseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_covseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_covseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_covseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_covseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_covseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_covseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_covseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_covseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_dnaseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_dnaseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq__p_COMPGEN=_shtab_compgen_files
_shtab_genpipes_dnaseq___pairs_COMPGEN=_shtab_compgen_files
_shtab_genpipes_longread_dnaseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_longread_dnaseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_longread_dnaseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_longread_dnaseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_longread_dnaseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_longread_dnaseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_longread_dnaseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_longread_dnaseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_methylseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_methylseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_methylseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_methylseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_methylseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_methylseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_methylseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_methylseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_nanopore_covseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_nanopore_covseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_nanopore_covseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_nanopore_covseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_nanopore_covseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_nanopore_covseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_nanopore_covseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_nanopore_covseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_rnaseq___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_rnaseq__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq__b_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq___batch_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_rnaseq_denovo_assembly___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_rnaseq_denovo_assembly__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly___design_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly__b_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_denovo_assembly___batch_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_light__c_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_light___config_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_light__o_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_rnaseq_light___output_dir_COMPGEN=_shtab_compgen_dirs
_shtab_genpipes_rnaseq_light__r_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_light___readsets_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_light__d_COMPGEN=_shtab_compgen_files
_shtab_genpipes_rnaseq_light___design_COMPGEN=_shtab_compgen_files

_shtab_genpipes_pos_0_choices=('ampliconseq' 'chipseq' 'covseq' 'dnaseq' 'longread_dnaseq' 'methylseq' 'nanopore_covseq' 'rnaseq' 'rnaseq_denovo_assembly' 'rnaseq_light' 'tools')
_shtab_genpipes__s_choices=('bash' 'zsh' 'tcsh')
_shtab_genpipes___print_completion_choices=('bash' 'zsh' 'tcsh')
_shtab_genpipes_ampliconseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_ampliconseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_ampliconseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_ampliconseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_chipseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_chipseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_chipseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_chipseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_chipseq__t_choices=('chipseq' 'atacseq')
_shtab_genpipes_chipseq___type_choices=('chipseq' 'atacseq')
_shtab_genpipes_covseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_covseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_covseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_covseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_dnaseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_dnaseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_dnaseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_dnaseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_dnaseq__t_choices=('germline_snv' 'germline_sv' 'germline_high_cov' 'somatic_tumor_only' 'somatic_fastpass' 'somatic_ensemble' 'somatic_sv')
_shtab_genpipes_dnaseq___type_choices=('germline_snv' 'germline_sv' 'germline_high_cov' 'somatic_tumor_only' 'somatic_fastpass' 'somatic_ensemble' 'somatic_sv')
_shtab_genpipes_longread_dnaseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_longread_dnaseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_longread_dnaseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_longread_dnaseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_longread_dnaseq__t_choices=('nanopore' 'revio')
_shtab_genpipes_longread_dnaseq___type_choices=('nanopore' 'revio')
_shtab_genpipes_methylseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_methylseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_methylseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_methylseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_methylseq__t_choices=('bismark' 'gembs' 'hybrid' 'dragen')
_shtab_genpipes_methylseq___type_choices=('bismark' 'gembs' 'hybrid' 'dragen')
_shtab_genpipes_nanopore_covseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_nanopore_covseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_nanopore_covseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_nanopore_covseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_nanopore_covseq__t_choices=('default' 'basecalling')
_shtab_genpipes_nanopore_covseq___type_choices=('default' 'basecalling')
_shtab_genpipes_rnaseq__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_rnaseq___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_rnaseq__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_rnaseq___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_rnaseq__t_choices=('stringtie' 'variants' 'cancer')
_shtab_genpipes_rnaseq___type_choices=('stringtie' 'variants' 'cancer')
_shtab_genpipes_rnaseq_denovo_assembly__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_rnaseq_denovo_assembly___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_rnaseq_denovo_assembly__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_rnaseq_denovo_assembly___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_rnaseq_denovo_assembly__t_choices=('trinity' 'seq2fun')
_shtab_genpipes_rnaseq_denovo_assembly___type_choices=('trinity' 'seq2fun')
_shtab_genpipes_rnaseq_light__j_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_rnaseq_light___job_scheduler_choices=('pbs' 'batch' 'daemon' 'slurm')
_shtab_genpipes_rnaseq_light__l_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_rnaseq_light___log_choices=('debug' 'info' 'warning' 'error' 'critical')
_shtab_genpipes_tools_pos_0_choices=('chunk_genpipes' 'csvToreadset' 'job2json_project_tracking' 'log_report' 'submit_genpipes' 'get_wrapper' 'validate_genpipes')
_shtab_genpipes_tools_log_report___loglevel_choices=('ERROR' 'WARNING' 'INFO' 'CRITICAL')
_shtab_genpipes_tools_submit_genpipes__S_choices=('slurm' 'pbs')
_shtab_genpipes_tools_validate_genpipes__p_choices=('ampliconseq' 'chipseq' 'covseq' 'dnaseq' 'methylseq' 'longread_dnaseq' 'nanopore_covseq' 'rnaseq' 'rnaseq_denovo_assembly' 'rnaseq_light')
_shtab_genpipes_tools_validate_genpipes___pipeline_choices=('ampliconseq' 'chipseq' 'covseq' 'dnaseq' 'methylseq' 'longread_dnaseq' 'nanopore_covseq' 'rnaseq' 'rnaseq_denovo_assembly' 'rnaseq_light')

_shtab_genpipes_pos_0_nargs=A...
_shtab_genpipes__h_nargs=0
_shtab_genpipes___help_nargs=0
_shtab_genpipes__v_nargs=0
_shtab_genpipes___version_nargs=0
_shtab_genpipes_ampliconseq__h_nargs=0
_shtab_genpipes_ampliconseq___help_nargs=0
_shtab_genpipes_ampliconseq___clean_nargs=0
_shtab_genpipes_ampliconseq__c_nargs=+
_shtab_genpipes_ampliconseq___config_nargs=+
_shtab_genpipes_ampliconseq___container_nargs=2
_shtab_genpipes_ampliconseq__f_nargs=0
_shtab_genpipes_ampliconseq___force_nargs=0
_shtab_genpipes_ampliconseq___json_pt_nargs=0
_shtab_genpipes_ampliconseq___sanity_check_nargs=0
_shtab_genpipes_ampliconseq___wrap_nargs=?
_shtab_genpipes_ampliconseq__v_nargs=0
_shtab_genpipes_ampliconseq___version_nargs=0
_shtab_genpipes_chipseq__h_nargs=0
_shtab_genpipes_chipseq___help_nargs=0
_shtab_genpipes_chipseq___clean_nargs=0
_shtab_genpipes_chipseq__c_nargs=+
_shtab_genpipes_chipseq___config_nargs=+
_shtab_genpipes_chipseq___container_nargs=2
_shtab_genpipes_chipseq__f_nargs=0
_shtab_genpipes_chipseq___force_nargs=0
_shtab_genpipes_chipseq___json_pt_nargs=0
_shtab_genpipes_chipseq___sanity_check_nargs=0
_shtab_genpipes_chipseq___wrap_nargs=?
_shtab_genpipes_chipseq__v_nargs=0
_shtab_genpipes_chipseq___version_nargs=0
_shtab_genpipes_covseq__h_nargs=0
_shtab_genpipes_covseq___help_nargs=0
_shtab_genpipes_covseq___clean_nargs=0
_shtab_genpipes_covseq__c_nargs=+
_shtab_genpipes_covseq___config_nargs=+
_shtab_genpipes_covseq___container_nargs=2
_shtab_genpipes_covseq__f_nargs=0
_shtab_genpipes_covseq___force_nargs=0
_shtab_genpipes_covseq___json_pt_nargs=0
_shtab_genpipes_covseq___sanity_check_nargs=0
_shtab_genpipes_covseq___wrap_nargs=?
_shtab_genpipes_covseq__v_nargs=0
_shtab_genpipes_covseq___version_nargs=0
_shtab_genpipes_dnaseq__h_nargs=0
_shtab_genpipes_dnaseq___help_nargs=0
_shtab_genpipes_dnaseq___clean_nargs=0
_shtab_genpipes_dnaseq__c_nargs=+
_shtab_genpipes_dnaseq___config_nargs=+
_shtab_genpipes_dnaseq___container_nargs=2
_shtab_genpipes_dnaseq__f_nargs=0
_shtab_genpipes_dnaseq___force_nargs=0
_shtab_genpipes_dnaseq___json_pt_nargs=0
_shtab_genpipes_dnaseq___sanity_check_nargs=0
_shtab_genpipes_dnaseq___wrap_nargs=?
_shtab_genpipes_dnaseq__v_nargs=0
_shtab_genpipes_dnaseq___version_nargs=0
_shtab_genpipes_dnaseq___profyle_nargs=0
_shtab_genpipes_longread_dnaseq__h_nargs=0
_shtab_genpipes_longread_dnaseq___help_nargs=0
_shtab_genpipes_longread_dnaseq___clean_nargs=0
_shtab_genpipes_longread_dnaseq__c_nargs=+
_shtab_genpipes_longread_dnaseq___config_nargs=+
_shtab_genpipes_longread_dnaseq___container_nargs=2
_shtab_genpipes_longread_dnaseq__f_nargs=0
_shtab_genpipes_longread_dnaseq___force_nargs=0
_shtab_genpipes_longread_dnaseq___json_pt_nargs=0
_shtab_genpipes_longread_dnaseq___sanity_check_nargs=0
_shtab_genpipes_longread_dnaseq___wrap_nargs=?
_shtab_genpipes_longread_dnaseq__v_nargs=0
_shtab_genpipes_longread_dnaseq___version_nargs=0
_shtab_genpipes_methylseq__h_nargs=0
_shtab_genpipes_methylseq___help_nargs=0
_shtab_genpipes_methylseq___clean_nargs=0
_shtab_genpipes_methylseq__c_nargs=+
_shtab_genpipes_methylseq___config_nargs=+
_shtab_genpipes_methylseq___container_nargs=2
_shtab_genpipes_methylseq__f_nargs=0
_shtab_genpipes_methylseq___force_nargs=0
_shtab_genpipes_methylseq___json_pt_nargs=0
_shtab_genpipes_methylseq___sanity_check_nargs=0
_shtab_genpipes_methylseq___wrap_nargs=?
_shtab_genpipes_methylseq__v_nargs=0
_shtab_genpipes_methylseq___version_nargs=0
_shtab_genpipes_nanopore_covseq__h_nargs=0
_shtab_genpipes_nanopore_covseq___help_nargs=0
_shtab_genpipes_nanopore_covseq___clean_nargs=0
_shtab_genpipes_nanopore_covseq__c_nargs=+
_shtab_genpipes_nanopore_covseq___config_nargs=+
_shtab_genpipes_nanopore_covseq___container_nargs=2
_shtab_genpipes_nanopore_covseq__f_nargs=0
_shtab_genpipes_nanopore_covseq___force_nargs=0
_shtab_genpipes_nanopore_covseq___json_pt_nargs=0
_shtab_genpipes_nanopore_covseq___sanity_check_nargs=0
_shtab_genpipes_nanopore_covseq___wrap_nargs=?
_shtab_genpipes_nanopore_covseq__v_nargs=0
_shtab_genpipes_nanopore_covseq___version_nargs=0
_shtab_genpipes_rnaseq__h_nargs=0
_shtab_genpipes_rnaseq___help_nargs=0
_shtab_genpipes_rnaseq___clean_nargs=0
_shtab_genpipes_rnaseq__c_nargs=+
_shtab_genpipes_rnaseq___config_nargs=+
_shtab_genpipes_rnaseq___container_nargs=2
_shtab_genpipes_rnaseq__f_nargs=0
_shtab_genpipes_rnaseq___force_nargs=0
_shtab_genpipes_rnaseq___json_pt_nargs=0
_shtab_genpipes_rnaseq___sanity_check_nargs=0
_shtab_genpipes_rnaseq___wrap_nargs=?
_shtab_genpipes_rnaseq__v_nargs=0
_shtab_genpipes_rnaseq___version_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly__h_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___help_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___clean_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly__c_nargs=+
_shtab_genpipes_rnaseq_denovo_assembly___config_nargs=+
_shtab_genpipes_rnaseq_denovo_assembly___container_nargs=2
_shtab_genpipes_rnaseq_denovo_assembly__f_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___force_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___json_pt_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___sanity_check_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___wrap_nargs=?
_shtab_genpipes_rnaseq_denovo_assembly__v_nargs=0
_shtab_genpipes_rnaseq_denovo_assembly___version_nargs=0
_shtab_genpipes_rnaseq_light__h_nargs=0
_shtab_genpipes_rnaseq_light___help_nargs=0
_shtab_genpipes_rnaseq_light___clean_nargs=0
_shtab_genpipes_rnaseq_light__c_nargs=+
_shtab_genpipes_rnaseq_light___config_nargs=+
_shtab_genpipes_rnaseq_light___container_nargs=2
_shtab_genpipes_rnaseq_light__f_nargs=0
_shtab_genpipes_rnaseq_light___force_nargs=0
_shtab_genpipes_rnaseq_light___json_pt_nargs=0
_shtab_genpipes_rnaseq_light___sanity_check_nargs=0
_shtab_genpipes_rnaseq_light___wrap_nargs=?
_shtab_genpipes_rnaseq_light__v_nargs=0
_shtab_genpipes_rnaseq_light___version_nargs=0
_shtab_genpipes_tools_pos_0_nargs=A...
_shtab_genpipes_tools__h_nargs=0
_shtab_genpipes_tools___help_nargs=0
_shtab_genpipes_tools_chunk_genpipes__h_nargs=0
_shtab_genpipes_tools_chunk_genpipes___help_nargs=0
_shtab_genpipes_tools_csvToreadset__h_nargs=0
_shtab_genpipes_tools_csvToreadset___help_nargs=0
_shtab_genpipes_tools_job2json_project_tracking__h_nargs=0
_shtab_genpipes_tools_job2json_project_tracking___help_nargs=0
_shtab_genpipes_tools_log_report__h_nargs=0
_shtab_genpipes_tools_log_report___help_nargs=0
_shtab_genpipes_tools_log_report___quiet_nargs=0
_shtab_genpipes_tools_log_report__q_nargs=0
_shtab_genpipes_tools_submit_genpipes__h_nargs=0
_shtab_genpipes_tools_submit_genpipes___help_nargs=0
_shtab_genpipes_tools_get_wrapper__h_nargs=0
_shtab_genpipes_tools_get_wrapper___help_nargs=0
_shtab_genpipes_tools_validate_genpipes__h_nargs=0
_shtab_genpipes_tools_validate_genpipes___help_nargs=0


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_${completed_positional_actions}" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_genpipes() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_genpipes
  local word_index=0
  local pos_only=0 # "--" delimeter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" ${this_word} "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" ${this_word} "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_${completed_positional_actions}" true
      fi
    else
      pos_only=1 # "--" delimeter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  if [[ $pos_only = 0 && "${completing_word}" == -* ]]; then
    # optional argument started: use option strings
    COMPREPLY=( $(compgen -W "${current_option_strings[*]}" -- "${completing_word}") )
  else
    # use choices & compgen
    local IFS=$'\n' # items may contain spaces, so delimit using newline
    COMPREPLY=( $([ -n "${current_action_compgen}" ] \
                  && "${current_action_compgen}" "${completing_word}") )
    unset IFS
    COMPREPLY+=( $(compgen -W "${current_action_choices[*]}" -- "${completing_word}") )
  fi

  return 0
}

complete -o filenames -F _shtab_genpipes genpipes
