[DEFAULT]
#Modules
module_amber=mugqic/amber/4.0
module_cobalt=mugqic/cobalt/1.16
module_pave=mugqic/pave/1.6
module_purple=mugqic/purple/4.0.1
module_circos=mugqic/circos/0.69-6
module_R=mugqic/R_Bioconductor/4.1.0_3.13
module_chord=mugqic/chord/2.1.1

hmftools_dir = $MUGQIC_INSTALL_HOME/genomes/hmftools
#purple files
gc_profile_file=%(assembly_dir)s/annotations/%(scientific_name)s.%(assembly)s.GC_profile.1000bp.cnp
somatic_hotspots_file=%(hmftools_dir)s/hmf_pipeline_resources.%(assembly_alias2)s/variants/KnownHotspots.somatic.%(assembly_alias2)s.vcf.gz
germline_hotspots_file=%(hmftools_dir)s/hmf_pipeline_resources.%(assembly_alias2)s/variants/KnownHotspots.germline.%(assembly_alias2)s.vcf.gz
driver_gene=%(hmftools_dir)s/hmf_pipeline_resources.%(assembly_alias2)s/common/DriverGenePanel.%(assembly_alias2)s.tsv
ensembl_data=%(hmftools_dir)s/hmf_pipeline_resources.%(assembly_alias2)s/common/ensembl_data


[clairS]
nb_jobs = 23
cluster_cpu = 6
cluster_walltime = 8:00:00
cluster_mem = 30G
threads = 5
other_options = --enable_indel_calling --print_germline_calls --enable_clair3_germline_output
model_path = $MUGQIC_INSTALL_HOME/genomes/rerio/clair3_models/r1041_e82_400bps_sup_v430
platform = ont_r10_dorado_sup_5khz_ssrs

[merge_filter_clairS]
module_bcftools=mugqic/bcftools/develop
cluster_cpu = 8
cluster_mem = 16G

[savana]
cluster_cpu = 16
cluster_walltime = 3:00:00
cluster_mem = 30G
threads = 11
cna_threads = 15
mapq = 7
cn_step_change = --main_cn_step_change 2
contigs = %(assembly_dir)s/annotations/contigs.chr.hg38.txt

[savana2cnvkit]
module_c3g_tools = mugqic/c3g_tools/2.12.13
cluster_cpu = 1
cluster_walltime = 0:30:00
cluster_mem = 4G

[amber]
module_java=mugqic/java/openjdk-jdk-19.0.1
java_other_options=-XX:+UseParallelGC -XX:ParallelGCThreads=1 -Dsamjdk.buffer_size=4194304 -Djdk.lang.Process.launchMechanism=vfork
ram=16000M
threads=8
loci=%(assembly_dir)s/annotations/%(scientific_name)s.%(assembly)s.GermlineHetPon.vcf.gz

[cobalt]
module_java=mugqic/java/openjdk-jdk-19.0.1
java_other_options=-XX:+UseParallelGC -XX:ParallelGCThreads=1 -Dsamjdk.buffer_size=4194304 -Djdk.lang.Process.launchMechanism=vfork
ram=16000M
threads=8
gc_profile=%(assembly_dir)s/annotations/%(scientific_name)s.%(assembly)s.GC_profile.1000bp.cnp

[purple]
module_java = mugqic/java/openjdk-jdk-19.0.1
module_perl = mugqic/perl/5.34.0
#java_other_options = -XX:+UseParallelGC -XX:ParallelGCThreads=1 -Dsamjdk.buffer_size=4194304 -Djdk.lang.Process.launchMechanism=vfork
ram = 30G
cluster_cpu = %(QUART_CPU)s
threads = 8
cluster_walltime = 3:00:00
cluster_mem = 32G
gc_profile=%(gc_profile_file)s
ensembl_data_dir=%(ensembl_data)s
somatic_hotspots=%(somatic_hotspots_file)s
germline_hotspots=%(germline_hotspots_file)s
driver_gene_panel=%(driver_gene)s

[chord]
module_java=mugqic/java/openjdk-jdk-21.0.2
module_R=mugqic/R_Bioconductor/4.5.1_3.21
cluster_cpu=4
cluster_mem=12G
cluster_walltime=2:00:00

[format2pcgr]
module_mugqic_tools = mugqic/c3g_tools/2.12.13
cluster_cpu = 1
cluster_walltime = 0:30:00
cluster_mem = 4G

[report_cpsr]
options_v2=--force_overwrite --secondary_findings --gwas_findings --panel_id 0 --pgx_findings
assembly=grch38
cluster_cpu=%(PINT_CPU)s
cluster_mem=36G
cluster_walltime=3:00:0

[report_pcgr]
options_v2=--force_overwrite --vep_buffer_size 500 --vep_regulatory --vcf2maf 
tumor_type=--tumor_site 0
tumor_options=--tumor_dp_tag TDP --tumor_af_tag TVAF
normal_options=--control_dp_tag NDP --control_af_tag NVAF --control_af_max 0.03
mutsig_options=--estimate_signatures
tmb_options=--estimate_tmb
msi_options=--estimate_msi
assembly=grch38
assay=--assay WGS
cluster_cpu=%(QUART_CPU)s
cluster_mem=36G
cluster_walltime=3:00:0

[report_djerba]
module_djerba = mugqic/djerba/1.10.2
module_wkhtmltopdf = mugqic/wkhtmltopdf/0.12.6
cluster_mem = 1G
cluster_cpu = 1
cluster_walltime = 0:10:00
# djerba report options:
assay_description = LongRead DnaSeq - Nanopore Paired Somatic Protocol
oncokb_cache =
project_name =
# oncokb token is required to run djerba step
oncokb_token =
custom_html_directory = $MUGQIC_INSTALL_HOME/software/djerba/supporting_files/custom_formatting/plain_html
template_dir = $MUGQIC_INSTALL_HOME/software/djerba/supporting_files/custom_formatting/genpipes6_supplement
# define cancer type with OncoTree code if known
cancer_type = 