name: Run PyTest

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['dev', 'main']
  push:
    branches: ['main']

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4.1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pdm install -d -G testing
        pdm add pytest flake8

    - name: Lint with flake8
      run: |
        pdm run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv
        pdm run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv
